backend:
  name: git-gateway
  repo: KuluGary/eg-lierno-frontend-nextjs
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "blog"
    label: "Blog"
    folder: "content"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "string" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Fecha", name: "date", widget: "date", default: "", format: "MMM Do YY", date_format: true }
      - { label: "Imagen principal", name: "image", widget: "image" }
      - { label: "Descripción de la imagen", name: "imageAlt", widget: "string" }
      - { label: "Cuerpo del texto", name: "body", widget: "markdown" }
